// Placement trigger — app-layer adapter that starts the 摸底 flow for the
// current book. Target concepts are the book's chapters (interim chapter-level
// identity, same as the quiz evidence wiring); the pool is capped above the
// CAT maximum so the selector has room, and diagnostic item content is
// generated by the configured LLM (co-processor) through the unified gateway.

import { loadExistingBookSkill } from "@/lib/book-skill/trigger";
import { useSettingsStore } from "@/stores/settings-store";
import { fallbackContentService } from "@readany/core/ai";
import { createBookSkillLlmClient } from "@readany/core/book-skill";
import {
  PLACEMENT_MAX_ITEMS,
  answerPlacementItem as coreAnswerPlacementItem,
  finalizePlacement as coreFinalizePlacement,
  createSqliteLearnerStores,
  ensureChapterConceptIdentity,
  generatePlacementItems,
  getActivePlacementSession,
  startPlacementSession,
} from "@readany/core/learner";
import type { PlacementSession, PlacementVerdict } from "@readany/core/learner";
import type { Book } from "@readany/core/types";

/** CAT maximum is 20 answered items; keep a small selection buffer. */
const PLACEMENT_POOL_CAP = PLACEMENT_MAX_ITEMS + 4;

async function placementConcepts(book: Book) {
  const skill = await loadExistingBookSkill(book);
  if (skill) {
    return skill.manifest.readany.chapters.map((chapter) => ({
      conceptId: `readany:book:${book.id}:chapter:${chapter.chapterIndex}`,
      chapterIndex: chapter.chapterIndex,
      title: chapter.title,
    }));
  }
  const chapters = await fallbackContentService.getChapters(book);
  return chapters
    .filter((chapter) => chapter.content.trim().length > 0)
    .map((chapter) => ({
      conceptId: `readany:book:${book.id}:chapter:${chapter.index}`,
      chapterIndex: chapter.index,
      title: chapter.title || `Chapter ${chapter.index + 1}`,
    }));
}

export async function createPlacementEngineDeps() {
  return {
    clock: { now: (): Date => new Date() },
    ...createSqliteLearnerStores(),
  };
}

/** Start the placement flow for a book. Fail-closed when the generated pool is
 * below the CAT minimum. Uses the book's existing skill chapters when present,
 * otherwise the canonical chapter extraction. Placement start is a concept-
 * identity registration point (PR-015) for the capped pool. */
export async function startBookPlacement(book: Book): Promise<PlacementSession> {
  const deps = await createPlacementEngineDeps();
  const allConcepts = await placementConcepts(book);
  const concepts = allConcepts.slice(0, PLACEMENT_POOL_CAP);
  await Promise.all(
    concepts.map((concept) =>
      ensureChapterConceptIdentity(
        deps.identity,
        { bookId: book.id, chapterIndex: concept.chapterIndex, title: concept.title },
        deps.clock.now().getTime(),
      ),
    ),
  );
  const aiConfig = useSettingsStore.getState().aiConfig;
  const llm = await createBookSkillLlmClient(aiConfig);
  const items = await generatePlacementItems({
    bookTitle: book.meta.title,
    concepts,
    llm,
    idPrefix: `placement:${book.id}`,
  });
  return startPlacementSession(deps, items);
}

/** The active placement session, if one is in progress. */
export async function getActivePlacement(): Promise<PlacementSession | null> {
  return getActivePlacementSession(await createPlacementEngineDeps());
}

/** Apply one answer to a placement session and persist it. */
export async function answerPlacement(
  session: PlacementSession,
  itemId: string,
  correct: boolean,
): Promise<PlacementSession> {
  return coreAnswerPlacementItem(await createPlacementEngineDeps(), session, itemId, correct);
}

/** Finalize a placement session: guarded mastery writes + answer-only evidence. */
export async function finalizePlacementSession(
  session: PlacementSession,
): Promise<PlacementVerdict> {
  return coreFinalizePlacement(await createPlacementEngineDeps(), session);
}
